---
version: "2.2"
services:
  postgres:
    image: postgres:16.3
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employees

  pgadmin:
    image: dpage/pgadmin4:8.9
    depends_on:
      - postgres
    ports:
      - 5480:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    links:
      - "postgres:pgsql-server"

